/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syntomic_ffi_FFIDemo */

#ifndef _Included_com_syntomic_ffi_FFIDemo
#define _Included_com_syntomic_ffi_FFIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syntomic_ffi_FFIDemo
 * Method:    dayOfWeek
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_syntomic_ffi_FFIDemo_dayOfWeek
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
